[FEATURE] Add progress bar to BuildQueueCommand
AOEpeople/crawler pull request #636
Opened 2020-10-17 12:48 UTC by carstendietrich

## Description
Adds a simple Symfony progress bar when using the execute mode to have a visual representation of the crawling progress.

Also removed some dead code from the command since the configuration keys are always returend as array. Fixed a wrong PHPDoc return type in CrawlerController as well.

Resolves #627 partially.

**I have**

- [x] Checked that CGL are followed
- [ ] Checked that the Tests are still working
- [ ] Added description to CHANGELOG.md (github-handle is optional)
- [ ] Added tests for the new code

2020-10-17 12:49 UTC, carstendietrich commented
TODO:
- [ ] Figure out functional tests in DDEV context
- [ ] Update changelog
- [ ] Add tests for progress bar output

2020-10-17 20:16 UTC, tomasnorre commented
> TODO:
> 
>     * [ ]  Figure out functional tests in DDEV context

If you go to the `.docker` directory in the repository root, and do `docker-composer up -d` you will get and docker-mysql running. 
After that you can do `composer test:functional` 

Otherwise perhaps a small read here:
https://github.com/AOEpeople/crawler/blob/master/CONTRIBUTING.md#running-tests-without-local-development-environment

2020-10-19 19:24 UTC, carstendietrich commented
> > TODO:
> > ```
> > * [ ]  Figure out functional tests in DDEV context
> > ```
> 
> If you go to the `.docker` directory in the repository root, and do `docker-composer up -d` you will get and docker-mysql running.
> After that you can do `composer test:functional`
> 
> Otherwise perhaps a small read here:
> https://github.com/AOEpeople/crawler/blob/master/CONTRIBUTING.md#running-tests-without-local-development-environment

Got the integration tests up and running by reusing the stuff from the composer.json but changing the database values to match DDEV.

Currently, it seems that the progress bar interferes with PHPUnit and fails the test case:
![cli](https://user-images.githubusercontent.com/3203968/96501445-a895b800-1250-11eb-8ccd-4af25f05d605.png)

When checking the assertions with XDebug everything looks fine, no clue whats the issue 😭 :
![php_debug](https://user-images.githubusercontent.com/3203968/96501534-c3682c80-1250-11eb-91b6-badb45856c4e.png)

Any ideas? So far I only tested commands within unit tests using the Symfony `CommandTester` class..

2020-10-19 19:58 UTC, tomasnorre commented
Sorry, I don't have much experience with tests like this perhaps @bmack, @CDRO or @icanhazstring has some input here.

2020-10-26 21:12 UTC, carstendietrich commented
Argh, found the issue. Symfony `ProgressBar` outputs to `stderr` which lets PHPUnit think that there is an error. Redirecting the  `stderr` now to `stdout` during the test execution. Tests are now green.

2020-10-27 05:48 UTC, tomasnorre requested changes
I haven't tested the functionality yet, just added my comments.

2020-10-27 05:48 UTC, tomasnorre commented on Classes/Command/BuildQueueCommand.php
> -     * $ typo3 crawler:buildQueue 7 defaultConfiguration --depth 2 --mode exec
Please keep as it was, it is to show that it's the default confugation, not that the configuration is called default in the crawler devbox.

2020-10-27 05:48 UTC, tomasnorre commented on Classes/Command/BuildQueueCommand.php
> -        if (! is_array($configurationKeys)) {
Why is this removed??

2020-10-27 05:48 UTC, tomasnorre commented on Tests/Functional/Command/BuildQueueCommandTest.php
> +        $commandOutput = [];
Why change this? the CommandUtility::exec() returns a string

2020-10-27 18:02 UTC, carstendietrich commented on Classes/Command/BuildQueueCommand.php
> -        if (! is_array($configurationKeys)) {
`getConfigurationKeys` will always return an array so this code is never reached.

2020-10-27 18:03 UTC, carstendietrich commented on Tests/Functional/Command/BuildQueueCommandTest.php
> +        $commandOutput = [];
Oh seems like a leftover when I fiddled with different commands for executing.. restored the empty string.

2020-10-27 18:04 UTC, carstendietrich commented on Classes/Command/BuildQueueCommand.php
> -     * $ typo3 crawler:buildQueue 7 defaultConfiguration --depth 2 --mode exec
Ahhh thought it was a bug since the command didn't work in the dev box. good to know, restored it.

2020-10-27 18:08 UTC, tomasnorre reviewed
Thanks, Have a UserGroups as I write, so would need to test this before I can merge. 

But looks good from Code Point of View.

2020-10-27 18:40 UTC, tomasnorre commented
Test works as expected too @carstendietrich 
Anything else you want to do before merging?

The pretty output will be handle in #615 also with error handling.

2020-10-27 19:24 UTC, carstendietrich commented
> Test works as expected too @carstendietrich
> Anything else you want to do before merging?
> 
> The pretty output will be handle in #615 also with error handling.

Nope, guess I'm fine. Let's merge this one.

2020-10-27 19:26 UTC, tomasnorre approved these changes

2020-10-27 19:27 UTC, merged

2020-10-27 19:27 UTC, tomasnorre commented
It should actually have been a 9.2.0 version as it's a feature, but just say that after click merge. No big deal. It's at least not a breaking change.